# Generated by Django 4.2.19 on 2025-04-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
