# Generated by Django 4.2.19 on 2025-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0002_alter_twit_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
